name: module_chat
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter


  #vietinfo
  vietinfo_dev_core: ^0.0.5

  rxdart: ^0.24.1
  get_it: ^5.0.1
  sailor: ^0.7.1


  #firebase
  firebase_analytics: any
  firebase_messaging: ^6.0.9
  firebase_core: any
  flutter_local_notifications: ^1.4.4+4
  overlay_support: ^1.0.5


  flutter_bloc: ^6.0.6

  intl: ^0.16.1
  path_provider: ^1.6.24
  #  path: ^1.7.0
  camera: ^0.5.8+11
  #video thumbnail
  video_thumbnail: ^0.2.4
  open_file: ^3.0.1

  dio: ^3.0.10


  flutter_screenutil: ^2.3.0
  flushbar: ^1.10.4

  percent_indicator: ^2.1.5


  #
  vibration: ^1.7.1

  # add this line to your dependencies
  # image_pickers: ^1.0.8+7
  image_picker: ^0.6.7+14
  file_picker: 2.0.10
  video_player: ^1.0.1
  flutter_image_compress: ^0.7.0
  photo_view: ^0.10.3
  #data local
  sqflite: ^1.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
